### ISSUE TITLE
Make it possible to compile without gettext

### ISSUE THREAD

**Issue by ismaell** [axel-download-accelerator/axel#127]

**Comment by ismaell** [comment]
Fixed by commit bd4130621c44ef615d1eee6260102537524acdff.

**Comment by eribertomota** [comment]
2017-10-05 10:02 GMT-03:00 Ismael Luceno <notifications@github.com>:

> Closed #127 <https://github.com/axel-download-accelerator/axel/issues/127>
> .
>
>

Humm... Is it a good idea?

**Comment by ismaell** [comment]
Why should it be required?

**Comment by eribertomota** [comment]
2017-10-05 15:59 GMT-03:00 Ismael Luceno <notifications@github.com>:

> Why should it be required?
>
>
>
To provide translations to users. It is default in most programs because
basic users are not able to build using several options. Maybe an option
--without-gettext can be a good idea. However, it is my opnion and I may be
wrong.

**Comment by ismaell** [comment]
Does not `--disable-nls` get rid of `gettext` for users that need to compile without it?

**Comment by eribertomota** [comment]
2017-10-08 20:35 GMT-03:00 Ismael Luceno <notifications@github.com>:

> Does not --disable-nls get rid of gettext for users that need to compile
> without it?
>
>

Hum, you appear be right. Thanks.
