### ISSUE TITLE
use the readme.txt cannot install this software

### ISSUE THREAD

**Issue by Golden-proteogenomics** [axel-download-accelerator/axel#323]
the data form this this picture 
![图片](https://user-images.githubusercontent.com/50616816/93298766-6c70d100-f826-11ea-95af-075619e992ee.png)
and use the direction in readme files which description like "./configure && make && make install". However，the result of this command in computer is what cannot find this files, then the same thing is when i  find this the configure file. So, I want to know why？

**Comment by ismaell** [comment]
If the `configure` file doesn't exist, that probably means you're **building from** a copy of **the repository instead of from a release tarball**.

It **isn't equivalent.**

The same section provides instructions on how to generate the build system in that case.

However, I strongly recommend using release tarballs unless you know exactly what you're doing.
