### ISSUE TITLE
Replace standard library string.h functions with dynamic string ones

### ISSUE THREAD

**Issue by davidpolverari** [axel-download-accelerator/axel#64]
The usage of a dynamic string library, such as SDS - Simple Dynamic Strings (https://github.com/antirez/sds), would help getting rid of buffer overflows, by using dynamic heap-allocated strings instead of fixed-sized stack-allocated ones. In the particular case of SDS, it even provides an implementation that is compatible with good old C strings, making it easier to make the transition and to interface with other C libraries whenever needed.

**Comment by ismaell** [comment]
Doesn't avoid the need to rewrite the code, and static analysis can catch these issues and more, so I don't see the advantage (I speak from experience, I wrote a similar library for InitNG back in 2006 and it was a waste of time).

Interestingly, GCC 7 is spitting out some warnings, if anyone wants to try to fix those before the code is replaced.

**Comment by davidpolverari** [comment]
Yes, rewriting some code will be needed. Static analysis can really catch some issues, but will require us to fix the code, while using a dynamic string library would avoid those issues in the first place, making it easier to implement new features that depend on string manipulation without off-by-one or buffer overflow bugs. If it is deemed useful, I can create a topic branch and slowly try to migrate existing code to test this approach.

**Comment by ismaell** [comment]
My plan is to replace all the code anyway, as in complete rewrite, for the reasons you mentioned, plus it's unclean and there's a lot of wasteful use of memory. Perhaps you could help with that in the process (otherwise we would end with lots of conflicts between the branches).

But, what I've been thinking about, is that it would be useful to have an iovec-like structure to allow to build substrings that share storage with the original; we could build all upon that. For example, I've just been rewritting the function that fills `conn_t`, and such a struct is the next step to allow sharing a single copy of the URL for all the fields of `conn_t` (we need to keep the URL around anyway).

**Comment by ismaell** [comment]
I was talking about https://github.com/eribertomota/axel/pull/63.

**Comment by ismaell** [comment]
Not going to happen, it seems. Re-open if there's interest.
